name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # You can specify other versions or add more, e.g., [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Run ShiftLeft Scan for SAST
      uses: shiftleftsecurity/scan-action@master
      with:
        type: sast

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: "auto" # Autodetects the languages in the repo or you can specify manually 
      # Performs the actual analysis
    
    - name: Analyze
      uses: github/codeql-action/analyze@v1    

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run tests
      run: npm test